In [2]:
import pandas as pd

df = pd.read_csv("vdjdb.txt", sep='\t')

# display DataFrame
df.describe()

         complex.id   vdjdb.score
count  92771.000000  92771.000000
mean   10089.612379      0.196699
std    10197.643859      0.567001
min        0.000000      0.000000
25%        0.000000      0.000000
50%     7402.000000      0.000000
75%    18998.000000      0.000000
max    30594.000000      3.000000

In [4]:
df.isnull().sum()

complex.id             0
gene                   0
cdr3                   0
v.segm               101
j.segm              1145
species                0
mhc.a                  0
mhc.b                  0
mhc.class              0
antigen.epitope        0
antigen.gene          62
antigen.species        0
reference.id        1511
method                 0
meta                   0
cdr3fix                0
vdjdb.score            0
web.method             0
web.method.seq         0
web.cdr3fix.nc         0
web.cdr3fix.unmp       0
dtype: int64

In [5]:
df = df.drop(columns=['reference.id', 'method','meta', 'cdr3fix','web.method','web.cdr3fix.unmp','web.method.seq', 'web.cdr3fix.nc'])

In [6]:
null_mask = df.isnull().any(axis=1)
null_rows = df[null_mask]

In [5]:
df = df.dropna()

In [6]:
df.head()

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,vdjdb.score
0,1,TRA,CIVRAPGRADMRF,TRAV26-1*01,TRAJ43*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,Nef,HIV-1,2
1,1,TRB,CASSYLPGQGDHYSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,Nef,HIV-1,2
2,0,TRB,CASSFEAGQGFFSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,Nef,HIV-1,2
3,2,TRA,CAVPSGAGSYQLTF,TRAV20*01,TRAJ28*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,Nef,HIV-1,2
4,2,TRB,CASSFEPGQGFYSNQPQHF,TRBV13*01,TRBJ1-5*01,HomoSapiens,HLA-B*08,B2M,MHCI,FLKEKGGL,Nef,HIV-1,2

In [11]:
pip install git+https://github.com/kmayerb/tcrdist3.git@0.2.1

Collecting git+https://github.com/kmayerb/tcrdist3.git@0.2.1
  Cloning https://github.com/kmayerb/tcrdist3.git (to revision 0.2.1) to c:\users\bayan alsaghier\appdata\local\temp\pip-req-build-irzguh23
  Resolved https://github.com/kmayerb/tcrdist3.git to commit 49c6554f16ad7f20f50d7303a8ac75268f5f601f
Requirement already satisfied: pandas>=0.24.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.4.2)
Requirement already satisfied: numpy>=1.16.4 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.21.5)
Requirement already satisfied: parasail>=1.1.17 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.3.4)
Requirement already satisfied: scipy>=1.4.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.7.3)
Requirement already satisfied: pwseqdist>=0.6 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.6)
Requirement already satisfied: numba in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.55.1)
Requirement already satisfied: zipdist>=0.1.5 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.1.5)
Requirement already satisfied: fishersapi in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.5)
Requirement already satisfied: hierdiff>=0.4 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.9)
Requirement already satisfied: palmotif>=0.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.4)
Requirement already satisfied: tcrsampler>=0.1.9 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.1.9)
Requirement already satisfied: parmap>=1.5.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.7.0)
Requirement already satisfied: olga>=1.2.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (1.2.4)
Requirement already satisfied: dill>=0.3.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrdist3==0.2.0) (0.3.8)
Requirement already satisfied: statsmodels>=0.10 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from hierdiff>=0.4->tcrdist3==0.2.0) (0.13.2)
Requirement already satisfied: jinja2>=2.10.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from hierdiff>=0.4->tcrdist3==0.2.0) (2.11.3)
Requirement already satisfied: joblib>=0.16 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from hierdiff>=0.4->tcrdist3==0.2.0) (1.1.0)
Requirement already satisfied: fisher in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from fishersapi->tcrdist3==0.2.0) (0.1.14)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from jinja2>=2.10.1->hierdiff>=0.4->tcrdist3==0.2.0) (2.0.1)
Requirement already satisfied: matplotlib in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from palmotif>=0.2->tcrdist3==0.2.0) (3.5.1)
Requirement already satisfied: svgwrite in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from palmotif>=0.2->tcrdist3==0.2.0) (1.4.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from pandas>=0.24.2->tcrdist3==0.2.0) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from pandas>=0.24.2->tcrdist3==0.2.0) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.24.2->tcrdist3==0.2.0) (1.16.0)
Requirement already satisfied: patsy>=0.5.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from statsmodels>=0.10->hierdiff>=0.4->tcrdist3==0.2.0) (0.5.2)
Requirement already satisfied: packaging>=21.3 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from statsmodels>=0.10->hierdiff>=0.4->tcrdist3==0.2.0) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from packaging>=21.3->statsmodels>=0.10->hierdiff>=0.4->tcrdist3==0.2.0) (3.0.4)
Requirement already satisfied: progress>=1.5 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from tcrsampler>=0.1.9->tcrdist3==0.2.0) (1.6)
Requirement already satisfied: feather-format>=0.4.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from zipdist>=0.1.5->tcrdist3==0.2.0) (0.4.1)
Requirement already satisfied: pyarrow>=0.4.0 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from feather-format>=0.4.1->zipdist>=0.1.5->tcrdist3==0.2.0) (15.0.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from matplotlib->palmotif>=0.2->tcrdist3==0.2.0) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from matplotlib->palmotif>=0.2->tcrdist3==0.2.0) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from matplotlib->palmotif>=0.2->tcrdist3==0.2.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from matplotlib->palmotif>=0.2->tcrdist3==0.2.0) (0.11.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from numba->tcrdist3==0.2.0) (0.38.0)
Requirement already satisfied: setuptools in c:\users\bayan alsaghier\anaconda3\lib\site-packages (from numba->tcrdist3==0.2.0) (61.2.0)
Building wheels for collected packages: tcrdist3
  Building wheel for tcrdist3 (setup.py): started
  Building wheel for tcrdist3 (setup.py): finished with status 'done'
  Created wheel for tcrdist3: filename=tcrdist3-0.2.0-py3-none-any.whl size=2108359 sha256=7ee6c8bc7055ae4ba3c994f3ae686a109b06916261a90e9d198bdb1396b85078
  Stored in directory: C:\Users\Bayan Alsaghier\AppData\Local\Temp\pip-ephem-wheel-cache-lshu8eus\wheels\6d\0f\5e\ec65196960b5c2093241651b801db59c57d1baf944ffa5f1ba
Successfully built tcrdist3
Installing collected packages: tcrdist3
  Attempting uninstall: tcrdist3
    Found existing installation: tcrdist3 0.2.2
    Uninstalling tcrdist3-0.2.2:
      Successfully uninstalled tcrdist3-0.2.2
Successfully installed tcrdist3-0.2.0
Note: you may need to restart the kernel to use updated packages.

  Running command git clone -q https://github.com/kmayerb/tcrdist3.git 'C:\Users\Bayan Alsaghier\AppData\Local\Temp\pip-req-build-irzguh23'
  Running command git checkout -q 49c6554f16ad7f20f50d7303a8ac75268f5f601f

In [12]:
"""
If you just want a 'tcrdistances' using pre-set default setting.

    You can access distance matrices:
        tr.pw_alpha     - alpha chain pairwise distance matrix
        tr.pw_beta      - alpha chain pairwise distance matrix
        tr.pw_cdr3_a_aa - cdr3 alpha chain distance matrix
        tr.pw_cdr3_b_aa - cdr3 beta chain distance matrix
"""
import pandas as pd
from tcrdist.repertoire import TCRrep

df = pd.read_csv("https://raw.githubusercontent.com/kmayerb/tcrdist2/API2/tcrdist/test_files_compact/dash.csv")
tr = TCRrep(cell_df = df, 
            organism = 'mouse', 
            chains = ['alpha','beta'], 
            db_file = 'alphabeta_gammadelta_db.tsv')

ImportError: cannot import name 'path_to_default_models' from 'tcrdist.paths' (C:\Users\Bayan Alsaghier\anaconda3\lib\site-packages\tcrdist\paths.py)

In [17]:
df = df.drop(columns=['epitope'])

KeyError: "['epitope'] not found in axis"

In [16]:
df

   ID   A    B
0   1  10  100
1   1  20  200
2   2  30  300
3   2  40  400

In [64]:
import pandas as pd
from tcrdist.repertoire import TCRrep

tr = TCRrep(cell_df = df, 
            organism = 'mouse', 
            chains = ['alpha','beta'], 
            db_file = 'alphabeta_gammadelta_db.tsv')

tr.pw_cdr3_a_aa

array([[ 0, 28, 25, ..., 27, 27, 19],
       [28,  0, 26, ..., 24, 24, 28],
       [25, 26,  0, ..., 25, 25, 31],
       ...,
       [27, 24, 25, ...,  0,  4, 24],
       [27, 24, 25, ...,  4,  0, 28],
       [19, 28, 31, ..., 24, 28,  0]], dtype=int16)

In [15]:
import pandas as pd


import pandas as pd

# Example DataFrame
data = {'ID': [1, 1, 2, 2],
        'A': [10, 20, 30, 40],
        'B': [100, 200, 300, 400]}
df = pd.DataFrame(data)

# Define a custom function to concatenate values
def concatenate_values(x):
    return ', '.join(str(value) for value in x)

# Group by ID and aggregate values using the custom function
merged_df = df.groupby('ID').agg({'A': concatenate_values, 'B': concatenate_values}).reset_index()

print(merged_df)

   ID       A         B
0   1  10, 20  100, 200
1   2  30, 40  300, 400

In [22]:
import pandas as pd

# Creating the dataframe
data = {
    "gene": ["TRA", "TRB", "TRB", "TRA", "TRB","TRA", "TRB"],
    "cdr3": ["CIVRAPGRADMRF", "CASSYLPGQGDHYSNQPQHF", "CASSFEAGQGFFSNQPQHF", "CAVPSGAGSYQLTF", "CASSFEPGQGFYSNQPQHF","CAVPSGAGSYQLTF", "CASSFEPGQGFYSNQPQHF"],
    "v.segm": ["TRAV26-1*01", "TRBV13*01", "TRBV13*01", "TRAV20*01", "TRBV13*01","TRAV20*01", "TRBV13*01"],
    "j.segm": ["TRAJ43*01", "TRBJ1-5*01", "TRBJ1-5*01", "TRAJ28*01", "TRBJ1-5*01","TRAJ28*01", "TRBJ1-5*01"],
    "species": ["HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens","HomoSapiens", "HomoSapiens"],
    "subject_id": ["005", "005", "065", "200", "200","200","200"]
}

df = pd.DataFrame(data)

# Filter data for TRA and TRB separately
df_TRA = df[df['gene'] == 'TRA'].rename(columns={'cdr3': 'cdr3_TRA', 'v.segm': 'v.segm_TRA'})
df_TRB = df[df['gene'] == 'TRB'].rename(columns={'cdr3': 'cdr3_TRB', 'j.segm': 'j.segm_TRB'})

# Merge the dataframes
result = pd.merge(df_TRA[['cdr3_TRA', 'v.segm_TRA', 'species', 'subject_id']], df_TRB[['cdr3_TRB', 'j.segm_TRB', 'species', 'subject_id']], on=['species', 'subject_id'])

result

,cdr3_TRA,v.segm_TRA,species,subject_id,cdr3_TRB,j.segm_TRB
0,CIVRAPGRADMRF,TRAV26-1*01,HomoSapiens,005,CASSYLPGQGDHYSNQPQHF,TRBJ1-5*01
1,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,200,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01
2,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,200,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01
3,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,200,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01
4,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,200,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01

In [24]:
import pandas as pd

# Creating the dataframe
data = {
    "gene": ["TRA", "TRB", "TRB", "TRA", "TRB"],
    "cdr3": ["CIVRAPGRADMRF", "CASSYLPGQGDHYSNQPQHF", "CASSFEAGQGFFSNQPQHF", "CAVPSGAGSYQLTF", "CASSFEPGQGFYSNQPQHF"],
    "v.segm": ["TRAV26-1*01", "TRBV13*01", "TRBV13*01", "TRAV20*01", "TRBV13*01"],
    "j.segm": ["TRAJ43*01", "TRBJ1-5*01", "TRBJ1-5*01", "TRAJ28*01", "TRBJ1-5*01"],
    "species": ["HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens"],
    "subject_id": ["005", "005", "065", "005", "005"]
}

df = pd.DataFrame(data)

# Filter data for TRA and TRB separately
df_TRA = df[df['gene'] == 'TRA'].rename(columns={'cdr3': 'cdr3_TRA', 'v.segm': 'v.segm_TRA'})
df_TRB = df[df['gene'] == 'TRB'].rename(columns={'cdr3': 'cdr3_TRB', 'j.segm': 'j.segm_TRB'})

# Merge the dataframes
result = pd.merge(df_TRA[['cdr3_TRA', 'v.segm_TRA', 'species', 'subject_id']], df_TRB[['cdr3_TRB', 'j.segm_TRB', 'species', 'subject_id']], on=['species', 'subject_id'])

result

,cdr3_TRA,v.segm_TRA,species,subject_id,cdr3_TRB,j.segm_TRB
0,CIVRAPGRADMRF,TRAV26-1*01,HomoSapiens,005,CASSYLPGQGDHYSNQPQHF,TRBJ1-5*01
1,CIVRAPGRADMRF,TRAV26-1*01,HomoSapiens,005,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01
2,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,005,CASSYLPGQGDHYSNQPQHF,TRBJ1-5*01
3,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,005,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01

In [26]:
import pandas as pd

# Creating the dataframe
data = {
    "gene": ["TRA", "TRB", "TRB", "TRA", "TRB"],
    "cdr3": ["CIVRAPGRADMRF", "CASSYLPGQGDHYSNQPQHF", "CASSFEAGQGFFSNQPQHF", "CAVPSGAGSYQLTF", "CASSFEPGQGFYSNQPQHF"],
    "v.segm": ["TRAV26-1*01", "TRBV13*01", "TRBV13*01", "TRAV20*01", "TRBV13*01"],
    "j.segm": ["TRAJ43*01", "TRBJ1-5*01", "TRBJ1-5*01", "TRAJ28*01", "TRBJ1-5*01"],
    "species": ["HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens"],
    "subject_id": ["005", "005", "065", "005", "005"]
}

df = pd.DataFrame(data)

# Filter data for TRA and TRB separately
df_TRA = df[df['gene'] == 'TRA'].rename(columns={'cdr3': 'cdr3_TRA', 'v.segm': 'v.segm_TRA'})
df_TRB = df[df['gene'] == 'TRB'].rename(columns={'cdr3': 'cdr3_TRB', 'j.segm': 'j.segm_TRB'})

# Merge the dataframes based on species and subject_id
result = pd.merge(df_TRA[['cdr3_TRA', 'v.segm_TRA', 'species', 'subject_id']], df_TRB[['cdr3_TRB', 'j.segm_TRB', 'species', 'subject_id']], on=['species', 'subject_id'])

result

,cdr3_TRA,v.segm_TRA,species,subject_id,cdr3_TRB,j.segm_TRB
0,CIVRAPGRADMRF,TRAV26-1*01,HomoSapiens,005,CASSYLPGQGDHYSNQPQHF,TRBJ1-5*01
1,CIVRAPGRADMRF,TRAV26-1*01,HomoSapiens,005,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01
2,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,005,CASSYLPGQGDHYSNQPQHF,TRBJ1-5*01
3,CAVPSGAGSYQLTF,TRAV20*01,HomoSapiens,005,CASSFEPGQGFYSNQPQHF,TRBJ1-5*01

In [28]:
import pandas as pd

data = {
    "gene": ["TRA", "TRB", "TRB", "TRA", "TRB"],
    "cdr3": ["CIVRAPGRADMRF", "CASSYLPGQGDHYSNQPQHF", "CASSFEAGQGFFSNQPQHF", "CAVPSGAGSYQLTF", "CASSFEPGQGFYSNQPQHF"],
    "v.segm": ["TRAV26-1*01", "TRBV13*01", "TRBV13*01", "TRAV20*01", "TRBV13*01"],
    "j.segm": ["TRAJ43*01", "TRBJ1-5*01", "TRBJ1-5*01", "TRAJ28*01", "TRBJ1-5*01"],
    "species": ["HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens", "HomoSapiens"],
    "subject_id": ["005", "005", "065", "005", "005"]
}

df = pd.DataFrame(data)

# Create a new DataFrame with the desired format
new_df = pd.DataFrame(columns=["cdr3_tra", "cdr3_trb", "v.segm_tra", "j.segm_tra", "v.segm_trb", "j.segm_trb", "species", "subject_id"])

# Extracting rows with gene "TRA" and "TRB"
tra_row = df[df["gene"] == "TRA"].reset_index(drop=True)
trb_row = df[df["gene"] == "TRB"].reset_index(drop=True)

# Filling in the new DataFrame
new_df.loc[0] = [tra_row.loc[0, "cdr3"], trb_row.loc[0, "cdr3"], tra_row.loc[0, "v.segm"], tra_row.loc[0, "j.segm"], trb_row.loc[0, "v.segm"], trb_row.loc[0, "j.segm"], tra_row.loc[0, "species"], tra_row.loc[0, "subject_id"]]
new_df.loc[1] = [tra_row.loc[1, "cdr3"], trb_row.loc[1, "cdr3"], tra_row.loc[1, "v.segm"], tra_row.loc[1, "j.segm"], trb_row.loc[1, "v.segm"], trb_row.loc[1, "j.segm"], tra_row.loc[1, "species"], tra_row.loc[1, "subject_id"]]

new_df

,cdr3_tra,cdr3_trb,v.segm_tra,j.segm_tra,v.segm_trb,j.segm_trb,species,subject_id
0,CIVRAPGRADMRF,CASSYLPGQGDHYSNQPQHF,TRAV26-1*01,TRAJ43*01,TRBV13*01,TRBJ1-5*01,HomoSapiens,005
1,CAVPSGAGSYQLTF,CASSFEAGQGFFSNQPQHF,TRAV20*01,TRAJ28*01,TRBV13*01,TRBJ1-5*01,HomoSapiens,005

In [31]:
import pandas as pd

# Example dataframe
data = {
    'ID': [1, 1, 2, 2, 3],
    'Value': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

# Group by ID and create a dictionary of mini data frames
mini_dataframes = {group: df_group for group, df_group in df.groupby('ID')}

print(mini_dataframes)

{1:    ID  Value
0   1     10
1   1     20, 2:    ID  Value
2   2     30
3   2     40, 3:    ID  Value
4   3     50}

In [34]:
import pandas as pd

# Example dataframe
data = {
    'gene': ['TRA', 'TRB', 'TRA', 'TRB', 'TRA', 'TRB', 'TRA', 'TRB'],
    'cdr3': ['CAVPSGAGSYQLTF', 'CASSFEPGQGFYSNQPQHF', 'CAVPSGAGSYQLTF', 'CASSFEPGQGFYSNQPQHF', 'CAVPSGAGSYQLTF', 'CASSFEPGQGFYSNQPQHF', 'CAVPSGAGSYQLTF', 'CASSFEPGQGFYSNQPQHF'],
    'v.segm': ['TRAV20*01', 'TRBV13*01', 'TRAV20*01', 'TRBV13*01', 'TRAV20*01', 'TRBV13*01', 'TRAV20*01', 'TRBV13*01'],
    'j.segm': ['TRAJ28*01', 'TRBJ1-5*01', 'TRAJ28*01', 'TRBJ1-5*01', 'TRAJ28*01', 'TRBJ1-5*01', 'TRAJ28*01', 'TRBJ1-5*01'],
    'species': ['HomoSapiens', 'HomoSapiens', 'HomoSapiens', 'HomoSapiens', 'HomoSapiens', 'HomoSapiens', 'HomoSapiens', 'HomoSapiens'],
    'subject_id': [200, 200, 200, 200, 200, 200, 200, 200]
}
df = pd.DataFrame(data)

# Group by 'subject_id'
grouped_df = df.groupby('subject_id')

# Create a new dataframe
new_df = pd.DataFrame(columns=['cdr3_TRA', 'v.segm_TRA', 'j.segm_TRA', 'cdr3_TRB', 'v.segm_TRB', 'j.segm_TRB', 'species', 'subject_id'])
for _, group in grouped_df:
    # Extract 'TRA' and 'TRB' rows
    tra_row = group[group['gene'] == 'TRA'].squeeze()
    trb_row = group[group['gene'] == 'TRB'].squeeze()
    
    # Combine rows
    combined_row = {
        'cdr3_TRA': tra_row['cdr3'], 'v.segm_TRA': tra_row['v.segm'], 'j.segm_TRA': tra_row['j.segm'],
        'cdr3_TRB': trb_row['cdr3'], 'v.segm_TRB': trb_row['v.segm'], 'j.segm_TRB': trb_row['j.segm'],
        'species': tra_row['species'], 'subject_id': tra_row['subject_id']
    }
    
    # Append combined row to new dataframe
    new_df = new_df.append(combined_row, ignore_index=True)

new_df

C:\Users\Bayan Alsaghier\AppData\Local\Temp\ipykernel_30208\3949136658.py:32: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(combined_row, ignore_index=True)

,cdr3_TRA,v.segm_TRA,j.segm_TRA,cdr3_TRB,v.segm_TRB,j.segm_TRB,species,subject_id
0,0 CAVPSGAGSYQLTF 2 CAVPSGAGSYQLTF 4 C...,0 TRAV20*01 2 TRAV20*01 4 TRAV20*01 6...,0 TRAJ28*01 2 TRAJ28*01 4 TRAJ28*01 6...,1 CASSFEPGQGFYSNQPQHF 3 CASSFEPGQGFYSNQP...,1 TRBV13*01 3 TRBV13*01 5 TRBV13*01 7...,1 TRBJ1-5*01 3 TRBJ1-5*01 5 TRBJ1-5*0...,0 HomoSapiens 2 HomoSapiens 4 HomoSap...,0 200 2 200 4 200 6 200 Name: subj...

In [43]:
import pandas as pd

# Create the original dataframe
data = {
    'Something_ID': ['id1', 'id1', 'id2', 'id2', 'id3', 'id3'],
    'Description': ['TRA', 'TRB', 'TRA', 'TRB', 'TRA', 'TRB'],
    'Col1': [1.1, 1.3, 111, 87, 8.1, 57],
    'Col2': [0.2, 1.5, 1.8, 1.8, 1.7, 1.7],
    'Col3': ['s', 's', 's', 's', 's', 's'],
    'Col4': ['-', '-', '-', '-', '-', '-']
}

df = pd.DataFrame(data)

# Pivot the dataframe
df_pivot = df.pivot(index='Something_ID', columns='Description', values=['Col1', 'Col2', 'Col3', 'Col4'])

# Flatten the column multi-index
df_pivot.columns = ['_'.join(col).strip() for col in df_pivot.columns.values]

# Reorder columns
df_pivot = df_pivot[['Col1_TRA', 'Col2_TRB', 'Col3_TRA', 'Col4_TRA', 'Col1_TRB', 'Col2_TRA', 'Col3_TRB']]

# Print the dataframe
print(df_pivot)

             Col1_TRA Col2_TRB Col3_TRA Col4_TRA Col1_TRB Col2_TRA Col3_TRB
Something_ID
id1               1.1      1.5        s        -      1.3      0.2        s
id2             111.0      1.8        s        -     87.0      1.8        s
id3               8.1      1.7        s        -     57.0      1.7        s

In [44]:
import pandas as pd

# Create the dataframe
data = {
    "Something_ID": ["id1", "id1", "id2", "id2", "id3", "id3"],
    "Description": ["TRA", "TRB", "TRA", "TRB", "TRA", "TRB"],
    "Col1": [1.1, 1.3, 111, 87, 8.1, 57],
    "Col2": [0.1, 2.1, 3.1, 1.1, 5.1, 2.1],
    "Col3": [0.2, 1.5, 1.8, 1.8, 1.7, 1.7],
    "Col4": ["s", "s", "s", "s", "s", "s"]
}

df = pd.DataFrame(data)

# Pivot the dataframe
pivot_df = df.pivot(index="Something_ID", columns="Description")

# Flatten the multi-index columns
pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]

# Reset index
pivot_df.reset_index(inplace=True)

# Rename columns
pivot_df.columns = [
    'Something_ID',
    'Col1_TRA',
    'Col1_TRB',
    'Col2_TRA',
    'Col2_TRB',
    'Col3_TRA',
    'Col3_TRB',
    'Col4'
]

print(pivot_df)

ValueError: Length mismatch: Expected axis has 9 elements, new values have 8 elements

In [47]:
import pandas as pd

# Create the dataframe
data = {
    "Something_ID": ["id1", "id1", "id2", "id2", "id3", "id3"],
    "Description": ["TRA", "TRB", "TRA", "TRB", "TRA", "TRB"],
    "Col1": [1.1, 1.3, 111, 87, 8.1, 57],
    "Col2": [0.1, 2.1, 3.1, 1.1, 5.1, 2.1],
    "Col3": [0.2, 1.5, 1.8, 1.8, 1.7, 1.7],
    "Col4": ["s", "s", "s", "s", "s", "s"]
}

df = pd.DataFrame(data)

# Pivot the dataframe
pivot_df = df.pivot(index="Something_ID", columns="Description")

# Flatten the multi-index columns
pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]

# Reset index
pivot_df.reset_index(inplace=True)

# Rename columns
pivot_df.columns = [
    'Something_ID',
    'Col1_TRA',
    'Col1_TRB',
    'Col2_TRA',
    'Col2_TRB',
    'Col3_TRA',
    'Col3_TRB',
    'Col4_TRA',
    'Col4_TRB'
]

# Drop the unnecessary columns
pivot_df.drop(columns=['Col4_TRB'], inplace=True)

pivot_df

,Something_ID,Col1_TRA,Col1_TRB,Col2_TRA,Col2_TRB,Col3_TRA,Col3_TRB,Col4_TRA
0,id1,1.1,1.3,0.1,2.1,0.2,1.5,s
1,id2,111.0,87.0,3.1,1.1,1.8,1.8,s
2,id3,8.1,57.0,5.1,2.1,1.7,1.7,s

In [48]:
import pandas as pd

# Assuming df is your DataFrame
data = {
    "Something_ID": [1.1, 1.3, 111, 87, 8.1, 57],
    "Description": [0.1, 2.1, 3.1, 1.1, 5.1, 2.1],
    "Col1": [0.2, 1.5, 1.8, 1.8, 1.7, 1.7],
    "Col2": ['s', 's', 's', 'x', 'x', 'x']
}

df = pd.DataFrame(data)

# Splitting based on values in 'Col2'
df_s = df[df['Col2'] == 's']
df_x = df[df['Col2'] == 'x']

# Displaying the resulting DataFrames
print("DataFrame with 's' values:")
print(df_s)

print("\nDataFrame with 'x' values:")
print(df_x)

DataFrame with 's' values:
   Something_ID  Description  Col1 Col2
0           1.1          0.1   0.2    s
1           1.3          2.1   1.5    s
2         111.0          3.1   1.8    s

DataFrame with 'x' values:
   Something_ID  Description  Col1 Col2
3          87.0          1.1   1.8    x
4           8.1          5.1   1.7    x
5          57.0          2.1   1.7    x

In [49]:
import pandas as pd

# Assuming you have a DataFrame named df and a column named 'column_name'
# Replace 'column_name' with the actual name of the column you want to examine

# Example DataFrame
data = {'column_name': [1, 2, 3, 4, 5, 1, 2, 3]}
df = pd.DataFrame(data)

# Get unique values in the 'column_name' column
unique_values = df['column_name'].unique()

print(unique_values)

[1 2 3 4 5]

In [50]:
import pandas as pd

# Suppose df is your DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Current column order
print("Current column order:")
print(df)

# Define the new column order
new_column_order = ['C', 'A', 'B']

# Create a new DataFrame with the new column order
new_df = pd.DataFrame(columns=new_column_order)

# Copy data from original DataFrame to the new DataFrame
for column in new_column_order:
    new_df[column] = df[column]

# New DataFrame with the new column order and values preserved
print("\nNew DataFrame with the new column order:")
print(new_df)

Current column order:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

New DataFrame with the new column order:
   C  A  B
0  7  1  4
1  8  2  5
2  9  3  6

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

tcrs_encoded = pd.get_dummies(dfm_beta, columns=['gene','cdr3_b_aa','v_b_gene','j_b_gene','species'])
scaler = StandardScaler()
tcrs_scaled = scaler.fit_transform(tcrs_encoded)
pca = PCA(n_components=2)
tcrs_pca = pca.fit_transform(tcrs_scaled)

plt.figure(figsize=(8, 6))
plt.scatter(tcrs_pca[:, 0], tcrs_pca[:, 1], c=dfm_beta['vdjdb.score'], cmap='viridis')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('TCR PCA')
plt.colorbar(label='vdjdb.score')
plt.show()

NameError: name 'dfm_beta' is not defined

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt


# Drop the 'Score' column as it's not needed for dimensionality reduction
data = dfp.drop(columns=['vdjdb.score'])

# Apply one-hot encoding to categorical variables
data_encoded = pd.get_dummies(data)

# Separate numerical columns
numerical_columns = ['vdjdb.score']

# Standardize numerical columns
scaler = StandardScaler()
data_encoded[numerical_columns] = scaler.fit_transform(data_encoded[numerical_columns])

# Apply PCA
pca = PCA(n_components=2)
pca_result = pca.fit_transform(data_encoded)

# Plot PCA result
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.scatter(pca_result[:, 0], pca_result[:, 1])
plt.title('PCA')

NameError: name 'dfp' is not defined